# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

steps:
- task: NodeTool@0

  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js AzurePL'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build AzurePL'

- task: ArchiveFiles@2
  displayName: 'Compress build'
  inputs:
    rootFolderOrFile: 'build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/dashboard.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'